[meta]
name = "ManiaExchange"
author = "Greep"
category = "TMX"
perms = "paid"
siteid = 154

version = "1.2.8"

[script]
optional_dependencies = [ "BetterChat", "ItemExchange", "NadeoServices" ]

exports = [ "src/Exports/Exports.as" ]
timeout = 0

#defines = [ "FORCE_API_DOWN" ]
# FORCE_API_DOWN : Forces the API to be "down" after loading for tags and seasons.
